# Generated by Django 4.2 on 2023-05-05 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
