# Generated by Django 4.2 on 2023-05-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.IntegerField(choices=[(0, 'HR'), (1, 'Candidate'), (2, 'Stuff')], default=0),
        ),
    ]
